"""预置任务模板（10 个）。"""

PRESET_TEMPLATES = [
    {
        "template_id": "code-review",
        "title": "代码审查",
        "description": "审查代码质量、安全性和可维护性",
        "category": "development",
        "difficulty": "中等",
        "task_prompt": "审查以下代码的质量、安全性和可维护性。请提供：1) 代码质量评分(1-10) 2) 发现的问题列表 3) 改进建议 4) 安全漏洞检查",
        "recommended_roles": ["executor", "reviewer"],
        "recommended_skills": ["code_review", "testing"],
        "expected_output": "",
        "icon": "🔍",
        "tags": [],
    },
    {
        "template_id": "api-design",
        "title": "API 设计",
        "description": "设计 RESTful API 接口",
        "category": "development",
        "difficulty": "中等",
        "task_prompt": "设计一个 RESTful API，包含：1) 端点定义(路径、方法、参数) 2) 请求/响应格式(JSON Schema) 3) 错误码定义 4) 认证方式 5) 使用示例",
        "recommended_roles": ["planner", "executor"],
        "recommended_skills": ["api_design", "backend_dev"],
        "expected_output": "",
        "icon": "🔌",
        "tags": [],
    },
    {
        "template_id": "unit-testing",
        "title": "单元测试编写",
        "description": "为模块编写全面的单元测试",
        "category": "testing",
        "difficulty": "简单",
        "task_prompt": "为指定模块编写全面的单元测试，覆盖：1) 正常路径 2) 边界条件 3) 错误处理 4) 异步操作。确保测试独立且可重复运行。",
        "recommended_roles": ["executor", "reviewer"],
        "recommended_skills": ["testing"],
        "expected_output": "",
        "icon": "🧪",
        "tags": [],
    },
    {
        "template_id": "doc-generation",
        "title": "文档生成",
        "description": "为项目生成技术文档",
        "category": "documentation",
        "difficulty": "简单",
        "task_prompt": "为项目生成技术文档，包含：1) 架构概述 2) API 参考 3) 使用示例 4) 部署指南 5) 常见问题",
        "recommended_roles": ["executor"],
        "recommended_skills": ["content_writing"],
        "expected_output": "",
        "icon": "📝",
        "tags": [],
    },
    {
        "template_id": "bug-fix",
        "title": "Bug 修复",
        "description": "分析并修复软件缺陷",
        "category": "development",
        "difficulty": "中等",
        "task_prompt": "分析并修复以下 bug：1) 复现步骤 2) 根因分析 3) 修复方案 4) 回归测试 5) 影响范围评估",
        "recommended_roles": ["executor", "reviewer"],
        "recommended_skills": ["testing", "code_review"],
        "expected_output": "",
        "icon": "🐛",
        "tags": [],
    },
    {
        "template_id": "refactor",
        "title": "代码重构",
        "description": "重构模块以提升代码质量",
        "category": "development",
        "difficulty": "高级",
        "task_prompt": "重构指定模块，目标：1) 提升可读性 2) 减少复杂度 3) 改善可测试性 4) 保持行为不变 5) 逐步迁移（不破坏现有功能）",
        "recommended_roles": ["planner", "executor", "reviewer"],
        "recommended_skills": ["code_review", "fullstack_dev"],
        "expected_output": "",
        "icon": "♻️",
        "tags": [],
    },
    {
        "template_id": "db-design",
        "title": "数据库设计",
        "description": "设计数据库 schema 和索引策略",
        "category": "development",
        "difficulty": "高级",
        "task_prompt": "设计数据库 schema：1) 实体关系图 2) 表结构(字段、类型、约束) 3) 索引策略 4) 迁移脚本 5) 查询优化建议",
        "recommended_roles": ["planner", "executor"],
        "recommended_skills": ["database", "backend_dev"],
        "expected_output": "",
        "icon": "🗄️",
        "tags": [],
    },
    {
        "template_id": "deploy-config",
        "title": "部署配置",
        "description": "创建 Docker 和 CI/CD 部署配置",
        "category": "devops",
        "difficulty": "中等",
        "task_prompt": "创建部署配置：1) Dockerfile(多阶段构建) 2) docker-compose.yml 3) 环境变量配置 4) 健康检查 5) 日志配置 6) 资源限制",
        "recommended_roles": ["executor", "monitor"],
        "recommended_skills": ["devops", "deployment"],
        "expected_output": "",
        "icon": "🚀",
        "tags": [],
    },
    {
        "template_id": "perf-optimization",
        "title": "性能优化",
        "description": "分析并优化系统性能",
        "category": "development",
        "difficulty": "高级",
        "task_prompt": "分析并优化性能：1) 性能基线测量 2) 瓶颈分析 3) 优化方案 4) 优化后测量 5) 回归预防",
        "recommended_roles": ["planner", "executor", "reviewer"],
        "recommended_skills": ["performance", "backend_dev"],
        "expected_output": "",
        "icon": "⚡",
        "tags": [],
    },
    {
        "template_id": "security-audit",
        "title": "安全审计",
        "description": "进行 OWASP 安全审计",
        "category": "development",
        "difficulty": "高级",
        "task_prompt": "进行安全审计：1) OWASP Top 10 检查 2) 输入验证 3) 认证/授权 4) 数据保护 5) 依赖扫描 6) 修复建议",
        "recommended_roles": ["reviewer", "executor"],
        "recommended_skills": ["security_audit", "code_review"],
        "expected_output": "",
        "icon": "🛡️",
        "tags": [],
    },
]
