import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  container: {
    display: 'flex',
    height: '100%',
    overflow: 'hidden',
  },
  leftPanel: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
  },
  rightPanel: {
    width: '280px',
    borderLeft: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(0,0,0,0.3)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  panelHeader: {
    padding: '12px 16px',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
  },
  panelTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#e2e8f0',
  },
  tabBar: {
    display: 'flex',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
  },
  tabBtn: {
    flex: 1,
    padding: '8px 4px',
    background: 'transparent',
    border: 'none',
    borderBottomWidth: '2px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    color: '#6b7280',
    fontSize: '11px',
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'all 0.15s',
  },
  tabBtnActive: {
    color: '#a78bfa',
    borderBottomColor: '#8b5cf6',
    background: 'rgba(139,92,246,0.05)',
  },
  tabContent: {
    flex: 1,
    overflowY: 'auto',
    padding: '12px',
  },
  sectionTitle: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#8b5cf6',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    marginBottom: '8px',
  },
  teamMember: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px',
    borderRadius: '6px',
    marginBottom: '4px',
    background: 'rgba(255,255,255,0.03)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255,255,255,0.06)',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  teamMemberSelected: {
    background: 'rgba(139,92,246,0.1)',
    borderColor: 'rgba(139,92,246,0.3)',
  },
  memberEmoji: {
    fontSize: '20px',
  },
  memberInfo: {
    flex: 1,
  },
  memberName: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#e2e8f0',
  },
  memberStatus: {
    fontSize: '11px',
    marginTop: '2px',
  },
  expandIcon: {
    fontSize: '10px',
    color: '#6b7280',
    marginLeft: 'auto',
  },
  agentDetail: {
    margin: '0 0 8px 8px',
    padding: '8px 12px',
    background: 'rgba(0,0,0,0.2)',
    borderRadius: '6px',
    border: '1px solid rgba(139,92,246,0.15)',
  },
  detailRow: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '4px 0',
    borderBottom: '1px solid rgba(255,255,255,0.04)',
  },
  detailLabel: {
    fontSize: '11px',
    color: '#6b7280',
  },
  detailValue: {
    fontSize: '11px',
    color: '#e2e8f0',
    textAlign: 'right' as const,
    maxWidth: '60%',
  },
  emptyState: {
    padding: '24px',
    textAlign: 'center' as const,
    color: '#6b7280',
    fontSize: '13px',
  },
  fileItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px',
    borderRadius: '6px',
    marginBottom: '4px',
    background: 'rgba(255,255,255,0.03)',
    border: '1px solid rgba(255,255,255,0.06)',
  },
  fileIcon: {
    fontSize: '16px',
  },
  fileInfo: {
    flex: 1,
    overflow: 'hidden',
  },
  fileName: {
    fontSize: '12px',
    color: '#e2e8f0',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  fileMeta: {
    fontSize: '10px',
    color: '#6b7280',
  },
  skillItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px',
    borderRadius: '6px',
    marginBottom: '4px',
    background: 'rgba(255,255,255,0.03)',
    border: '1px solid rgba(255,255,255,0.06)',
  },
  skillIcon: {
    fontSize: '16px',
  },
  skillInfo: {
    flex: 1,
    overflow: 'hidden',
  },
  skillName: {
    fontSize: '12px',
    color: '#e2e8f0',
    fontWeight: 600,
  },
  skillMeta: {
    fontSize: '10px',
    color: '#6b7280',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  taskItem: {
    padding: '10px 12px',
    marginBottom: '6px',
    borderRadius: '8px',
    background: 'rgba(255,255,255,0.03)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255,255,255,0.06)',
  },
  taskMain: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  taskInfo: {
    flex: 1,
    overflow: 'hidden',
  },
  taskDesc: {
    fontSize: '12px',
    color: '#e2e8f0',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    marginBottom: '2px',
  },
  taskMeta: {
    fontSize: '10px',
    color: '#6b7280',
  },
  taskStatus: {
    fontSize: '10px',
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: '10px',
    background: 'rgba(255,255,255,0.05)',
    flexShrink: 0,
  },
  subtaskList: {
    marginTop: '8px',
    paddingTop: '8px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'rgba(255,255,255,0.04)',
    marginLeft: '22px',
  },
  subtaskItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '6px 10px',
    marginBottom: '4px',
    borderRadius: '6px',
    background: 'rgba(0,0,0,0.2)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255,255,255,0.04)',
  },
  subtaskDesc: {
    flex: 1,
    fontSize: '11px',
    color: '#d1d5db',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  ruleItem: {
    padding: '10px 12px',
    marginBottom: '6px',
    borderRadius: '8px',
    background: 'rgba(255,255,255,0.03)',
    border: '1px solid rgba(255,255,255,0.06)',
  },
  ruleHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginBottom: '6px',
  },
  ruleTypeTag: {
    padding: '2px 8px',
    borderRadius: '10px',
    fontSize: '10px',
    fontWeight: 600,
  },
  ruleAction: {
    fontSize: '12px',
    color: '#e2e8f0',
    lineHeight: 1.5,
    marginBottom: '6px',
  },
  ruleKeywords: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '4px',
  },
  keywordTag: {
    padding: '2px 6px',
    borderRadius: '4px',
    fontSize: '10px',
    background: 'rgba(139,92,246,0.1)',
    color: '#a78bfa',
    border: '1px solid rgba(139,92,246,0.2)',
  },
  officeScene: {
    position: 'relative',
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    background: 'linear-gradient(135deg, #0a0a1a 0%, #1a1a3a 50%, #0a0a2a 100%)',
  },
  gridFloor: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(rgba(139,92,246,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(139,92,246,0.03) 1px, transparent 1px)',
    backgroundSize: '40px 40px',
  },
  neonGlow: {
    position: 'absolute',
    inset: 0,
    background: 'radial-gradient(ellipse at 50% 50%, rgba(139,92,246,0.08) 0%, transparent 60%)',
  },
  officeTitle: {
    position: 'absolute',
    top: '16px',
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '4px',
    zIndex: 10,
  },
  officeTitleText: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '16px',
    fontWeight: 700,
    color: '#e2e8f0',
    textShadow: '0 0 20px rgba(139,92,246,0.5)',
  },
  titleIcon: {
    fontSize: '20px',
  },
  officeTitleHint: {
    fontSize: '11px',
    color: '#6b7280',
  },
  workstation: {
    position: 'absolute',
    width: '64px',
    height: '56px',
    borderRadius: '10px',
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(0,0,0,0.4)',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    gap: '2px',
    transform: 'translate(-50%, -50%)',
    backdropFilter: 'blur(8px)',
    transition: 'all 0.3s ease',
    cursor: 'default',
    overflow: 'hidden',
  },
  screenGlow: {
    position: 'absolute',
    inset: -10,
    borderRadius: '16px',
    pointerEvents: 'none',
  },
  wsIcon: {
    fontSize: '18px',
    position: 'relative',
    zIndex: 1,
  },
  wsLabel: {
    fontSize: '9px',
    fontWeight: 600,
    fontFamily: 'monospace',
    position: 'relative',
    zIndex: 1,
  },
  wsAgentName: {
    fontSize: '8px',
    color: '#9ca3af',
    position: 'absolute',
    bottom: '4px',
    left: '50%',
    transform: 'translateX(-50%)',
    whiteSpace: 'nowrap' as const,
  },
  meetingTable: {
    position: 'absolute',
    left: '50%',
    top: '50%',
    transform: 'translate(-50%, -50%)',
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    border: '2px solid rgba(139,92,246,0.3)',
    background: 'rgba(139,92,246,0.05)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.5s ease',
  },
  meetingTableActive: {
    borderColor: 'rgba(139,92,246,0.6)',
    background: 'rgba(139,92,246,0.15)',
    boxShadow: '0 0 40px rgba(139,92,246,0.2)',
  },
  tableInner: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '4px',
  },
  tableIcon: {
    fontSize: '20px',
  },
  tableLabel: {
    fontSize: '10px',
    color: '#8b5cf6',
    fontWeight: 600,
  },
  agentEntity: {
    position: 'absolute',
    transform: 'translate(-50%, -50%)',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '4px',
    zIndex: 20,
  },
  agentAvatar: {
    width: '56px',
    height: '56px',
    borderRadius: '50%',
    border: '2px solid',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(0,0,0,0.6)',
    backdropFilter: 'blur(8px)',
    transition: 'all 0.3s ease',
  },
  agentLabel: {
    padding: '2px 8px',
    borderRadius: '8px',
    border: '1px solid',
    fontSize: '10px',
    fontWeight: 500,
    whiteSpace: 'nowrap' as const,
    backdropFilter: 'blur(8px)',
  },
  workingIndicator: {
    position: 'absolute',
    top: '-4px',
    right: '-4px',
    fontSize: '14px',
    animation: 'agent-glow-pulse 1.5s ease-in-out infinite',
  },
  officeControls: {
    position: 'absolute',
    bottom: '20px',
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 30,
  },
  startMeetingBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 24px',
    borderRadius: '12px',
    border: '1px solid rgba(139,92,246,0.5)',
    background: 'linear-gradient(135deg, rgba(139,92,246,0.3), rgba(59,130,246,0.3))',
    color: '#fff',
    fontSize: '14px',
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: 'inherit',
    backdropFilter: 'blur(12px)',
    boxShadow: '0 0 20px rgba(139,92,246,0.3)',
    transition: 'all 0.2s ease',
  },
  btnIcon: {
    fontSize: '16px',
  },
  statusItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '6px 0',
    borderBottom: '1px solid rgba(255,255,255,0.04)',
  },
  statusLabel: {
    fontSize: '11px',
    color: '#6b7280',
  },
  statusValue: {
    fontSize: '11px',
    color: '#e2e8f0',
    fontWeight: 500,
  },
}
