import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    padding: '20px',
    background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
    borderRadius: '16px',
    border: '1px solid #334155',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 600,
    color: '#f1f5f9',
  },
  statusBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 12px',
    background: '#1e293b',
    borderRadius: '20px',
    border: '1px solid #334155',
  },
  statusIcon: {
    fontSize: '14px',
  },
  statusText: {
    fontSize: '13px',
    fontWeight: 500,
  },
  tableArea: {
    position: 'relative',
    width: '100%',
    height: '320px',
    minHeight: '320px',
  },
  svg: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  centerStatus: {
    position: 'absolute',
    left: '50%',
    top: '50%',
    transform: 'translate(-50%, -50%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    zIndex: 10,
  },
  statusEmoji: {
    fontSize: '32px',
    lineHeight: 1,
  },
  statusLabel: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#94a3b8',
  },
  pulseRing: {
    position: 'absolute',
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    border: '2px solid #f59e0b',
    animation: 'pulse 2s ease-in-out infinite',
    pointerEvents: 'none',
  },
  agentPosition: {
    position: 'absolute',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    cursor: 'pointer',
    transition: 'transform 0.2s ease',
    zIndex: 20,
  },
  agentAvatarWrapper: {
    width: '60px',
    height: '60px',
    borderRadius: '50%',
    border: '3px solid',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#1e293b',
    transition: 'all 0.2s ease',
  },
  agentName: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#e2e8f0',
    textAlign: 'center',
    maxWidth: '70px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  agentRole: {
    fontSize: '10px',
    color: '#64748b',
  },
  speakingIndicator: {
    display: 'flex',
    gap: '3px',
    marginTop: '2px',
  },
  speakingDot: {
    width: '4px',
    height: '4px',
    borderRadius: '50%',
    background: '#f59e0b',
    animation: 'bounce 1s ease-in-out infinite',
  },
  controlSection: {
    display: 'flex',
    justifyContent: 'center',
    gap: '12px',
  },
  startButton: {
    padding: '10px 24px',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    boxShadow: '0 4px 12px rgba(59, 130, 246, 0.3)',
  },
  endButton: {
    padding: '10px 24px',
    background: 'linear-gradient(135deg, #ef4444 0%, #dc2626 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    boxShadow: '0 4px 12px rgba(239, 68, 68, 0.3)',
  },
  doneMessage: {
    fontSize: '14px',
    color: '#10b981',
    fontWeight: 500,
  },
  taskAssignSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    padding: '16px',
    background: '#1e293b',
    borderRadius: '12px',
    border: '1px solid #334155',
  },
  taskAssignHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  taskAssignTitle: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#e2e8f0',
  },
  selectedAgentLabel: {
    fontSize: '12px',
    color: '#3b82f6',
    fontWeight: 500,
  },
  taskInputRow: {
    display: 'flex',
    gap: '10px',
  },
  taskInput: {
    flex: 1,
    padding: '10px 14px',
    background: '#0f172a',
    border: '1px solid #334155',
    borderRadius: '8px',
    color: '#e2e8f0',
    fontSize: '13px',
    outline: 'none',
    transition: 'border-color 0.2s ease',
  },
  assignButton: {
    padding: '10px 20px',
    background: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    boxShadow: '0 4px 12px rgba(139, 92, 246, 0.3)',
  },
  agentList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  agentListTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  agentListItems: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  agentListItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    background: '#1e293b',
    borderRadius: '8px',
    border: '1px solid transparent',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  agentListDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
  },
  agentListName: {
    fontSize: '13px',
    fontWeight: 500,
    color: '#e2e8f0',
  },
  agentListRole: {
    fontSize: '11px',
    color: '#64748b',
  },
}
